name: .NET

on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.0
      env:
       ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
  
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
     
    - name: Restore NuGet Packages
      run: nuget restore BSFixer.sln
 
    - name: Build
      run: msbuild BSFixer.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
    # Artifact name
        name: result
    # A file, directory or wildcard pattern that describes what to upload
        path: BSFixer\bin\Release\BSFixer.exe
        
    - name: Generate release tag
      uses: amitsingh-007/next-release-tag@v1.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Create Release
  # You may pin to the exact commit or the version.
  # uses: ncipollo/release-action@58ae73b360456532aafd58ee170c045abbeaee37
      uses: ncipollo/release-action@v1.10.0
      with:
        artifact: result
        tag: ${{ env.next_release_version }}
        
    
